baseURL = 'https://nguyenwoong20.github.io/Myblog/'
languageCode = 'en-us'
title = 'Nguyenisrealll'
theme = "hugo-theme-stack"

[params]
  mainSections = ["post"]

  [params.article]
    toc = true
    readingTime = true

  [params.sidebar]
    emoji = "🎮"
    subtitle = "Crafting games"
    [params.sidebar.avatar]
      enabled = true
      local = false
      src = "img/avatar.png"

  [params.colorScheme]
    toggle = true
    default = "auto"

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"


  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "home"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"
    weight = 2
    [menu.main.params]
      icon = "messages"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
    [menu.main.params]
      icon = "user"

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 4
    [menu.main.params]
      icon = "archives"

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5
    [menu.main.params]
      icon = "search"

  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 6
    [menu.main.params]
      icon = "link"


  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/nguyenwoong20"
    weight = 1
    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/"
    weight = 2
    [menu.social.params]
      icon = "brand-twitter"

  [[menu.social]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/"
    weight = 3
    [menu.social.params]
      icon = "brand-youtube"