baseURL = 'https://nguyenwoong20.github.io/Myblog/'
languageCode = 'en-us'
title = 'Nguyenisrealll'
theme = "hugo-theme-stack"

# Suppress HTML warnings
[markup.goldmark.renderer]
  unsafe = true

# Suppress specific warnings
ignoreErrors = ["error-remote-getjson"]
ignoreLogs = ['warning-goldmark-raw-html', 'WARN .* The "twitter", "tweet", and "twitter_simple" shortcodes were deprecated', 'WARN .* The "gist" shortcode was deprecated']

[params]
  mainSections = ["post"]

  [params.author]
    name = "Nguyenisrealll"
    description = "Fullstack Developer from Vietnam 🇻🇳"
    bio = "Passionate about building scalable and efficient digital solutions. I work with modern web technologies to create amazing user experiences."
    longBio = "Tôi là một lập trình viên Fullstack giàu kinh nghiệm và đầy đam mê, chuyên xây dựng các giải pháp số có tính mở rộng và hiệu quả cao. Ở mảng frontend, tôi sử dụng Next.js, TypeScript và Tailwind CSS để tạo ra các giao diện UI/UX thân thiện, linh hoạt và dễ tiếp cận. Ở mảng backend, tôi phát triển các hệ thống mạnh mẽ bằng C#, Java cùng với các cơ sở dữ liệu như MySQL, MongoDB và SQL Server. Tôi cũng yêu thích việc phát triển ứng dụng di động bằng Android Studio và xây dựng trò chơi tương tác với Unity. Tôi là một kỹ sư có tinh thần hợp tác, cầu tiến, chú trọng chi tiết và luôn cam kết mang đến những ứng dụng có cấu trúc tốt, hiệu năng cao và trải nghiệm người dùng vượt trội trên nhiều nền tảng."
    location = "Vietnam 🇻🇳"
    avatar = "/img/avatar.png"
    email = "nguyenwoong20@gmail.com"
    
  [params.article]
    toc = true
    readingTime = true

  [params.sidebar]
    compact = false
    emoji = "🎮"
    subtitle = "nguyenwoong20"
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.png"

  [params.colorScheme]
    toggle = true
    default = "auto"

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"


  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "home"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"
    weight = 2
    [menu.main.params]
      icon = "messages"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
    [menu.main.params]
      icon = "user"

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 4
    [menu.main.params]
      icon = "archives"

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5
    [menu.main.params]
      icon = "search"

  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 6
    [menu.main.params]
      icon = "link"


  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/nguyenwoong20"
    weight = 1
    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/nguyen-woong-3961a8389/"
    weight = 2
    [menu.social.params]
      icon = "link"

  [[menu.social]]
    identifier = "Mail"
    name = "Mail"
    url = "https://youtube.com/"
    weight = 3
    [menu.social.params]
      icon = "brand-youtube"